apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  namespace: beachshirts
  labels:
    app: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: shopping
        ports:
        - containerPort: 50050
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  namespace: beachshirts
  labels:
    app: shopping
spec:
  ports:
  - name: shopping
    port: 50050
    protocol: TCP
  selector:
    app: shopping
            