apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
  namespace: beachshirts
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: delivery
        ports:
        - containerPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: beachshirts
  labels:
    app: delivery

spec:
  ports:
  - name: delivery
    port: 50054
    protocol: TCP
  selector:
    app: delivery
                      